#!/usr/bin/python

import re

import hackabot
from hackabot.client import Client

hbc = Client()
msg = hbc.readline()
nick = hbc.sent_by()

if re.search(r'^herp', msg, re.IGNORECASE):
    print "send %s: derp" %(nick)
