#!/usr/bin/env python

##HACKABOT_HELP##
# Give an out of context recent reddit comment for user
# !reddit [user]
##HACKABOT_HELP##

import requests
import json
from random import randint
import sys
import os
import re
from hackabot.client import Client


def get_comment(user):
    url = "http://reddit.com/user/%s/.json" % user

    r = requests.get(url)
    data = json.loads(r.content)
    if (data.has_key('error')):
        return data['error']

    restricted = ['&gt;', '&lt;']
    comments = data['data']['children']

    if (len(comments) < 1):
        return "No comments for %s" % user

    comments = [x for x in comments if x['data'].has_key('body')]
    comments = [x for x in comments if len(x['data']['body']) < 400]

    for word in restricted:
        comments = [x for x in comments if word not in x['data']['body']]

    ran = randint(0, len(comments)-1)
    return comments[ran]['data']['body']

def main():
    hbc = Client()
    msg = hbc.readline()
    nick = hbc.sent_by()
    user = ''

    m = re.match(r'^(?P<user>.*)$', msg)
    if m:
        user = m.group('user')
    else:
        print "send No user specified"
        return
    if (user == ''):
        print "send No user specified"
        return

    print "send %s" % get_comment(user)


if __name__ == "__main__":
    main()
